name: SnipMC
options:
  bundleIdPrefix: it.wende
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
targets:
  SnipMC:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
    info:
      path: Generated/Info.plist
      properties:
        CFBundleDisplayName: SnipMC
        CFBundleName: SnipMC
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright © 2026"
        CFBundleURLTypes:
          - CFBundleURLName: it.wende.snipmc
            CFBundleURLSchemes:
              - snipmc
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: it.wende.snipmc
        PRODUCT_NAME: SnipMC
        MARKETING_VERSION: "1.0.2"
        CURRENT_PROJECT_VERSION: "3"
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ENABLE_HARDENED_RUNTIME: false
        CODE_SIGN_IDENTITY: "-"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
schemes:
  SnipMC:
    build:
      targets:
        SnipMC: all
    run:
      config: Debug
